### ISSUE TITLE
302 older wiki pages to the newer wiki pages

### ISSUE THREAD

**Issue by gdestuynder** [mozilla/infosec.mozilla.org#10]
@fox2mike we have a list of pages on wikimo that we'll want to 302 (and eventually 301, or maybe just 301) redirect.
Ex:
https://wiki.mozilla.org/Security/Guidelines/OpenSSH 301 https://infosec.mozilla.org/guidelines/openssh

Mediawiki has an extension to enable this (which needs to be enabled) though this can also be done through other means. What's the recommended way?

**Comment by fox2mike** [comment]
I'd prefer to do this with Apache vs a Redirection plugin. What's the list of pages you'd like redirected?

**Comment by fox2mike** [comment]
Filed https://bugzilla.mozilla.org/show_bug.cgi?id=1422417 to track on our end.

**Comment by gdestuynder** [comment]
\o/
https://wiki.mozilla.org/Security/InfoSec => https://infosec.mozilla.org
https://wiki.mozilla.org/Security/Guidelines/ = > https://infosec.mozilla.org/guidelines/
https://wiki.mozilla.org/Security/Guidelines/OpenSSH => https://infosec.mozilla.org/guidelines/openssh
https://wiki.mozilla.org/Security/Guidelines/Key_Management => https://infosec.mozilla.org/guidelines/key_management
https://wiki.mozilla.org/Security/Guidelines/Kubernetes = > https://infosec.mozilla.org/guidelines/kubernetes
https://wiki.mozilla.org/Security/Guidelines/OpenID_Connect => https://infosec.mozilla.org/guidelines/openid_connect
https://wiki.mozilla.org/Security/Guidelines/SAML => https://infosec.mozilla.org/guidelines/saml
https://wiki.mozilla.org/Security/Guidelines/Web_Security => https://infosec.mozilla.org/guidelines/web_security
https://wiki.mozilla.org/Security/Fundamentals/ = > https://infosec.mozilla.org/fundamentals/
https://wiki.mozilla.org/Security/Fundamentals/Security_Principles => https://infosec.mozilla.org/fundamentals/security_principles.html
https://wiki.mozilla.org/Security/Fundamentals/Rationales => https://infosec.mozilla.org/fundamentals/rationales.html


Thanks!

**Comment by fox2mike** [comment]
@gdestuynder do you guys have a stage instance we can test these against before pushing to prod? (we could do stage -> prod tests, but was curious).

**Comment by gdestuynder** [comment]
@fox2mike you can do:
https://wiki.allizom.org/Security/InfoSec (stage) => https://infosec.mozilla.org/ (prod) as a stage test

https://infosec.mozilla.org/ itself is prod of course, though I don't think you need a stage destination (since prod on the destination side is otherwise untouched by this change)
If you need a stage though on that side of a reason I do not foresee, let me know and I can also make a stage branch there.
