### ISSUE TITLE
Headings aesthetics

### ISSUE THREAD

**Issue by speciale** [mozilla/infosec.mozilla.org#153]
The headings with `letter-spacing: -1px`; are hard to read when you have presbyopia

https://github.com/mozilla/infosec.mozilla.org/blob/31abc7052d68c1d51977c08a189c995029df9c62/docs/_sass/jekyll-theme-slate.scss#L61

**Comment by speciale** [comment]
Oh my! I see now that ALL the headings have changed in ALL the MDN sites! Thanks!

**Comment by gene1wood** [comment]
@speciale it should only affect infosec.mozilla.org (which is not related to MDN). If you're seeing a change in MDN it wasn't caused by this PR

**Comment by speciale** [comment]
My bad, you are right. There the headings has `letter-spacing: .035rem;` 
Thanks anyway
