### ISSUE TITLE
Add note to README about how to deploy site

### ISSUE THREAD

**Issue by gene1wood** [mozilla/infosec.mozilla.org#155]
If this is just native GitHub pages and any commit to `master` deploys that change to the site, mention that in the README, if not, indicate how to deploy the site

**Comment by MahamatTech** [comment]
Hello gene1wood, is there any problem that I can contribute too? did someone add to README  about how to deploy site?

**Comment by gene1wood** [comment]
Ah, yes this was actually fixed in #165 

But there may be other issues in the repo that you can contribute to.

**Comment by MahamatTech** [comment]
Hi @gene1wood , I will take a look, thanks
