### ISSUE TITLE
I cannot access the RRA template

### ISSUE THREAD

**Issue by ruitomas** [mozilla/infosec.mozilla.org#167]
I cannot access the RRA template using the link in the page. I get a "I can't access item" from google docs.
This is the link that I am redirecting to https://docs.google.com/document/d/1QMRdBLlQYqbn5lMmrOIBwS55Yh9fIYNp4dO3-HMyiyk/edit

Can you fix the permissions or the link?

Thank you

**Comment by gene1wood** [comment]
Oh shoot, a change to the parent "Shared Drive" that this document lives within overrode the share settings (it's set to be public), causing it to no longer be public. I'll find a place to move this to so that the "Shared Drive" settings don't override it.

**Comment by gene1wood** [comment]
Until #168 is merged you can use this copy of the template : https://docs.google.com/document/d/1uD-wofmkXBz5BVq49JQQqC3DnE77vwOPDSbHdWIve9s/edit

**Comment by gmaran23** [comment]
Thanks for the copy. 
Came here looking for the RRA template because the link at https://infosec.mozilla.org/guidelines/risk/rapid_risk_assessment.html is not available anymore due to access issues.
