### ISSUE TITLE
Query Regarding Maintenance Status of openssh.md 

### ISSUE THREAD

**Issue by hexkey** [mozilla/infosec.mozilla.org#189]
Hello,

what is current maintenance status of the [infosec.mozilla.org](https://github.com/mozilla/infosec.mozilla.org) and it's guidelines, some seem very outdated? 

cc @gene1wood @janbrasna @arroway @fkiriakos07 @hwine @LeoMcA

**Comment by gene1wood** [comment]
I'd say it's a bit outdated. We continue to make changes slowly to capture our team's security recommendations. So as far as status, I'd say maintained slowly.

**Comment by hexkey** [comment]
Thanks for update, and thanks for the effort to maintain it.
