### ISSUE TITLE
the floating header covers anchors when linking to an anchor

### ISSUE THREAD

**Issue by justdave** [mozilla/infosec.mozilla.org#25]
for example: https://infosec.mozilla.org/guidelines/openssh#recommended-safer-alternatives-to-ssh-agent-forwarding

The headline anchor that got linked to is behind the floating header so you can't see it.

Some hints I Googled up for how to fix this:
https://www.itsupportguides.com/knowledge-base/tech-tips-tricks/how-to-offset-anchor-tag-link-using-css/
http://nicolasgallagher.com/jump-links-and-viewport-positioning/

Can't vouch for their accuracy, but they look logical.

**Comment by gdestuynder** [comment]
thanks fixed by https://github.com/mozilla/infosec.mozilla.org/pull/32
