### ISSUE TITLE
Dead link under Assessing Security Risk

### ISSUE THREAD

**Issue by jwives** [mozilla/infosec.mozilla.org#41]
The FAIR Introduction link under [Assessing Security Risk](https://github.com/mozilla/infosec.mozilla.org/blob/1f6fdb86406dcb57005fe6225c9bbe9e350c6b0f/docs/guidelines/assessing_security_risk.md) is broken. This introduction PDF can be found elsewhere on the internet, though the creators no longer appear to want it to be freely available.

Perhaps a link to Wikipedia or another summary of the FAIR methodology would be worthwhile here.

**Comment by gdestuynder** [comment]
Thx!
