### ISSUE TITLE
Add using a password manager to the phishing guide

### ISSUE THREAD

**Issue by claudijd** [mozilla/infosec.mozilla.org#57]
For the sake of trying to minimize credential exposure.  One technique for users who don't commonly recognize URL changes to key sites (like authentication providers), if they use Password Manager autofills, the autofill will likely fail on said phishing site and this may help to contribute to the "what's wrong here" feeling that causes them to investigate further.

**Comment by atombrella** [comment]
https://github.com/mozilla/infosec.mozilla.org/blob/master/docs/guidelines/phishing.md#password-manager-behavior Isn't this already done here?
