### ISSUE TITLE
Broken images

### ISSUE THREAD

**Issue by c00kiemon5ter** [mozilla/infosec.mozilla.org#66]
Hello, 

while the docs as rendered through github look fine, on the main site the images are broken.
Here is an example:
https://github.com/mozilla/infosec.mozilla.org/blob/master/docs/guidelines/openssh.md
https://infosec.mozilla.org/guidelines/openssh

This should be fairly easy to fix ;)

**Comment by gdestuynder** [comment]
thanks for your report :)
note that I effectively inverted the behavior so that the image shows correctly on the site but not in github

i havent found a good way to show it in both places (CFN  vs github's pages behave differently)
