### ISSUE TITLE
Omit testing of Google Analytics cookies?  No apparent way to set Secure and/or HttpOnly.

### ISSUE THREAD

**Issue by feralreason** [mozilla/infosec.mozilla.org#70]
Still reporting "Cookies set without using the Secure flag or set over HTTP", even though all cookies except Google Analytics _ga _gat, _gid cookies are now set Secure and/or HttpOnly. There appears to be no way to set these GA cookies -- perhaps they should not be considered in the score?

**Comment by april** [comment]
Which site is this on? infosec.mozilla.org? I don't see this score for that site:

• No cookies detected

**Comment by floatingatoll** [comment]
Should this be filed against observatory? (I’ve mixed them up before.)

**Comment by april** [comment]
I'm not entirely sure why it's here at all, so I'm going to close this bug out.

@feralreason, if you feel that the Observatory is incorrectly giving you a score for a certain site, please open up a bug here:
https://github.com/mozilla/http-observatory/issues

Thanks!
