### ISSUE TITLE
Redirect infosec.mozilla.org domain

### ISSUE THREAD

**Issue by gdestuynder** [mozilla/infosec.mozilla.org#9]
cloudflare or zlb or ec2 reverse proxy

**Comment by gdestuynder** [comment]
assigned @claudijd in case you want to help with that, else feel free to deassign

**Comment by claudijd** [comment]
Filed Bug to get DNS deletegation to infosec-prod route53 (#1 & #2 above)...

https://bugzilla.mozilla.org/show_bug.cgi?id=1378838

**Comment by claudijd** [comment]
Sent an email to gene to get my AWS accounts re-instated.

**Comment by claudijd** [comment]
I have created the hosted zone in Route53, just waiting on delegation

**Comment by claudijd** [comment]
Delegation is confirmed

**Comment by gdestuynder** [comment]
@claudijd given the current ELB TLS security policy, these achieve "I" rating on the TLS observatory (eg https://observatory.mozilla.org/analyze.html?host=selfservice.mig.allizom.org#tls)
Shouldn't all the other things be taken care of through headers/HTML and thus work with the ELB?

**Comment by claudijd** [comment]
@gdestuynder I'm actually not familiar with ELB feature sets and their ability to modify headers/html.  If that is the case, I think we can get close with the web standards.

**Comment by floatingatoll** [comment]
As of recently, ELB only lets you add a specific set of headers, none of
which are useful for websec stuff. They seem to recommend API Gateway for
anything fancy.

 - R.

**Comment by gdestuynder** [comment]
@claudijd i made this: https://github.com/mozilla-iam/mozilla.oidc.accessproxy

**Comment by gdestuynder** [comment]
i've setup http://infosec.mozilla.org until this is resolved

**Comment by gdestuynder** [comment]
I've now setup cloudfront since it supports lambda functions to inject headers, and setup all necessary headers
https://observatory.mozilla.org/analyze.html?host=infosec.mozilla.org A+
